### ISSUE TITLE
Constructing Quantity from Quantity

### ISSUE THREAD

**Issue by ipcoder** [hgrecco/pint#1016]
Is this a desirable behaviour?
```python
a = Quantity([1,2], 'nm')
b = Quantity(a, 'mm')

isinstance(b.magnitude, Quantity) == True
```

**Comment by cpascual** [comment]
I am not sure if it is desirable, but at least it is coherent.

In order to support arbitrary objects as magnitudes (without explicit code on the part of pint), the pint constructor just accepts whatever object is passed as the magnitude. It does not try to guess your intentions.

For example, if you do `a = Quantity('123', 'm')`, then `a.magnitude` will be of type `str` (not numeric as some people may expect)

**Comment by cpascual** [comment]
BTW: regarding your example, I guess that the person doing it should do the following instead:

```python
a = Quantity([1,2], 'nm')
b = a.to('mm')
```

**Comment by hgrecco** [comment]
A mentioned by @cpascual, we do not limit the type of magnitude. If this is a common mistake, I would agree to implement a special behavior when the magnitude is a quantity.

**Comment by jthielen** [comment]
> [...] we do not limit the type of magnitude.

As of #959, this is not quite the case. There is now a list of "upcast types" which are not permitted inside of a `Quantity`, in order to preserve a well-defined type-casting hierarchy (see https://pint.readthedocs.io/en/0.10.1/numpy.html#Technical-Commentary).

So, it would not be that much of an aberration to have special behavior in the Quantity constructor when a Quantity is passed as value (in fact [there already is some when no units are passed](https://github.com/hgrecco/pint/blob/45efc2a1277faf5f0229303bfe2fe17167861149/pint/quantity.py#L177-L178)). I would argue that something is indeed needed, since a Quantity-within-Quantity is easy to mistakenly construct and has some rather unstable/unexpected behavior. But, should such a construction be prohibited, or simply warned but permitted?

**Comment by hgrecco** [comment]
There are these behaviours that I can see
1. Quantity(Q, units) uses Q as the magnitude
2. Quantity(Q) becomes Q and Quantity(Q, units) becomes Q.to(units)
3. Raise a TypeError Exception
4. (1) or (2) and raise a Warning

I would go with (3) as I do not see any reason to have (1), nor reason to use (2)

**Comment by ipcoder** [comment]
I can describe you a use case and we can see how it is representative or valid.

For the context: I am adding units support to a quite large package.
There are many modules and functions which mostly operate on `numpy` arrays.
My initial assessment was that changes are going to be only superficial, of 2 expected kinds:
1. The "proper" ones, where awareness of the units are essentiall
2. Places with explicit checking like `isinstane(x, np.ndarray)` - rare, but happens, also in third-party libraries like `matplotlib`. 

Back to the use case: consider functions expecting `Quantity` inputs (_Q-functions_). 

They could be called from many different functions, some of them not units-aware,
so that the inputs could be sometimes of `Quantity` and sometimes,  say `ndarray`.
A simple solution would be to align type to `Quantity` in beginning of the Q-functions, like:

```python 
x = Quantity(x, units)
```
or even write a decorator in some cases.

And as you can see here @hgrecco's option (2) may  simplify things by eliminating the need of explicit conversion logic in all such places.

So from this perspective option (2) seems altogether benefitial:
1. allows for cleaner code conversion to use Pint 
2. keeps things safe similar to option (3) when units are not convertible
3. so no hidden harm can be done, and I also like the fact that no `Q<Q nm> kg>` cases will not pass without error, since I can't imagine a valid situation for it.

**Comment by hgrecco** [comment]
I might be biased here, so I am open to hear more opinions on this.

Regarding adding units support to an existing package. What has worked for me is using `wraps`. In this way a units aware layer above the pure numeric base. This has the advantage of being cleaner and faster to run.

**Comment by dalito** [comment]
@hgrecco I would also prefer what you suggest that is to raise a type error for the case discussed.
