### ISSUE TITLE
Ugly ipython representation for Quantity

### ISSUE THREAD

**Issue by crusaderky** [hgrecco/pint#1052]
The ipython output for Quantity looks like a mix of str() for the magnitude and repr() for the unit:

```
In[1]: q = pint.Quantity(1, "kg")
In[2]: str(q)
Out[2]: '1 kilogram'
In[3]: repr(q)
Out[3]: "<Quantity(1, 'kilogram')>"
In[4]: q
Out[4]: 1 <Unit('kilogram')>
```

**Comment by 5igno** [comment]
Can you also comment on what would be pretty ipython representation for Quantity?

**Comment by crusaderky** [comment]
pick either repr or str, not a hybrid

**Comment by keewis** [comment]
`ipython` seems to call `_repr_pretty_` which delegates to both the magnitude and the unit, and since neither the magnitude nor the unit implement `_repr_pretty_`, the result is roughly `f"{repr(self.magnitude)} {repr(self.units)}"`.

To fix this, we probably need to figure out if we actually need the pretty version, and if yes, what it should look like.

**Comment by andrewgsavage** [comment]
I now get
```
q
1 kilogram
```

**Comment by keewis** [comment]
and I get `<Quantity(1, 'kilogram')>`. Either way this looks fine.
