### ISSUE TITLE
pint.Context example does not work and raises TypeError

### ISSUE THREAD

**Issue by mxdev88** [hgrecco/pint#1101]
Hi, trying to use Context but having some trouble with the example from the developer reference [pint.Context](https://pint.readthedocs.io/en/stable/developers_reference.html#pint.Context).

```
from pint import Context
from pint.util import UnitsContainer
timedim = UnitsContainer({'[time]': 1})
spacedim = UnitsContainer({'[length]': 1})


def f(time):
    'Time to length converter'
    return 3. * time


c = Context()
c.add_transformation(timedim, spacedim, f)
c.transform(timedim, spacedim, 2)
```

This raises the following error.

`TypeError: transform() missing 1 required positional argument: 'value'`

```
>>> pint.__version__
'0.11'
```

Please help. Thanks!

**Comment by clarkgwillison** [comment]
Ooh, yeah, that definitely was a problem in the docs. The call signature had changed but not the docstring that described how to use it. I believe it's fixed in the new release which contains fixes for many doctest errors: https://pint.readthedocs.io/en/stable/developers_reference.html#pint.Context

@hgrecco I think this can be closed
