### ISSUE TITLE
Conversion kilogauss to Tesla

### ISSUE THREAD

**Issue by rtesse** [hgrecco/pint#1105]
I updated my version of Pint from 0.9 to 0.11 and I have a dimensionality error when I execute this portion of code:
```
import pint
ureg = pint.UnitRegistry()
val = 1*ureg.T # 1 tesla
val_gauss = val.to('kilogauss') # -> DimensionalityError using v0.11
```
`Cannot convert from 'tesla' ([mass] / [current] / [time] ** 2) to 'kilogauss' ([mass] ** 0.5 / [length] ** 0.5 / [time])`

I think this is related to issue #1048  but I am not sure.

Regards,

Robin Tesse

**Comment by Jellby** [comment]
Enable the Gaussian context (`ureg.enable_contexts('Gaussian')`):

```
print(val_gauss)
9.999999997257989 kilogauss
```

**Comment by rtesse** [comment]
Dear @Jellby,
Thanks for your answer. 
The conversion works when I converted Tesla to Kilogauss but I still have a bug when I check the dimensionality.  There is a square root difference between Tesla and Gauss. Here is the python script:

```
import pint
ureg = pint.UnitRegistry()
ureg.enable_contexts('Gaussian')
val = 1*ureg.T # 1 tesla
val_gauss = val.to('kilogauss')

print(val, val_gauss)
print('Tesla: ', ureg.Quantity('T').dimensionality)
print('Gauss:', ureg.Quantity('gauss').dimensionality)
```

And the output:

```
1 tesla 9.999999997257989 kilogauss
Tesla:  [mass] / [current] / [time] ** 2
Gauss: [mass] ** 0.5 / [length] ** 0.5 / [time]
```

**Comment by Jellby** [comment]
Yes, that's correct. Gaussian units and SI units are not commensurate (they don't have the same dimensions). See https://en.wikipedia.org/wiki/Gaussian_units#Electromagnetic_unit_names

Any reference stating 1 T = 1e4 G is wrong, or inaccurate. It is true that a magnetic field with a strength of 1 when measured in T has a strength of 1e4 when measured in G, but the two quantities are not identical because they have different assumptions, which is reflected in their dimensions.

**Comment by chernals** [comment]
@Jellby Thanks for stating that explicitly. Indeed that's what I concluded, the shortcut 1T = 1e4 G is so common that we disregarded that.
