### ISSUE TITLE
Magnetic Units Conversion

### ISSUE THREAD

**Issue by BobMeyer48** [hgrecco/pint#1205]
There is a problem with magnetic units (Python 3.8, pint 0.16?) If I enter the value for Bfield as:

Bfield = 2000.0 ampere * meter * vacuum_permeability

print (Bfield.to(ureg.weber)) _**produces**_
0.0025132741242501204 weber

**_but_**
print (Bfield.to(ureg.maxwell)) **_produces_**

DimensionalityError: Cannot convert from 'ampere * meter * vacuum_permeability' ([length] ** 2 * [mass] / [current] / [time] ** 2) to 'maxwell' ([length] ** 1.5 * [mass] ** 0.5 / [time])

This is not a problem using pint with Python 2.7. The conversions work. It seems that the new version of pint is the problem. The unit "ureg.maxwell" is incorrectly dimensioned.
 
Any help would be appreciated.

**Comment by jules-ch** [comment]
You can use the Gaussian context to use Gaussian Units:

```python
with ureg.context("Gaussian"):
    print(Bfield.to(ureg.maxwell))
```
```python
251327.41235609783 Mx
```

Be careful, gaussian units are not dimensionnaly equivalent, since they were historically defined with CGS three base units system.

SI units & Gaussian units use 2 different definitions of the charge, when deriving Coulomb's Law.
They represents the same thing but only with different dimensions historically.
In pint's definition file, you can find :

```
[charge] = [current] * [time]
...
[gaussian_charge] = [length] ** 1.5 * [mass] ** 0.5 / [time]
```

More on this here:
    https://en.wikipedia.org/wiki/Centimetre%E2%80%93gram%E2%80%93second_system_of_units

So overall, in your case I'd say stick to SI Units if possible. If you need to use the Gaussian units with SI units, you should use the Gaussian context which uses the correct scaling factor.
The BIPM allows this : https://www.bipm.org/en/publications/si-brochure/table9

To enable globally this context you can do:

```python
ureg.enable_contexts("Gaussian")
```

[Here](https://pint.readthedocs.io/en/stable/contexts.html) the documentation on context.

**Comment by jules-ch** [comment]
Related #1048 & #1105

**Comment by BobMeyer48** [comment]
Thanks, that looks like a practical work-around.

**Comment by hgrecco** [comment]
Thanks @jules-ch for this great explanation. 

@BobMeyer48 I am not trying to be pedantic, but it is not really a workaround (in the sense of a hack), but rather a way to a sensible way to deal with two different systems.

@jules-ch I think we can add something like this to the docs as it is a very common source of question (in Pint and in Physics!).
