### ISSUE TITLE
square meter missing ?

### ISSUE THREAD

**Issue by LazzaAU** [hgrecco/pint#1247]
In Australia we use the square meter alot when talking about land size etc. Appears to me square meter isn't in the default registry and thought i'd mention it in case you thought it should be  :)

**Comment by cpascual** [comment]
Just curious (not opposing): what would be the advantage over simply using `ureg.m**2`?

**Comment by LazzaAU** [comment]
I only installed this repo today so not familiar with it yet. Now that it's been a few hours though  i'm starting to see the theory behind it , so probably no advantage , just documenting as i see it otherwise i forget  :)

**Comment by emphasize** [comment]
Those who want to parse a string need something appropriate for regex
I'm writeing a Mycroft skill wich parses the utterance to derive the units.

Added a couple of lines to default_en, that has done the trick with parsing.
square_millimeter = millimeter ** 2 = sqmm
square_centimeter = centimeter ** 2 = sqcm
square_meter = meter ** 2 = sqme

Since print(x.to(ureg.sqcm)) returned the correct value (12->120000) i think that is an approachable path.
Something to look out for? Something to further add?
Since i'm missing a couple and will along the way, i'm collecting them and PR them later.

Cheers

**Comment by emphasize** [comment]
definition as meter_

**Comment by jtuomist** [comment]
It seems that meter_square has a typo in its definition https://github.com/hgrecco/pint/blob/26e3a8d540d29bd1811c58794cc3d194e8600a3f/pint/xtranslated.txt#L6 and is defined as square kilometer!
