### ISSUE TITLE
Floating point issues

### ISSUE THREAD

**Issue by MarcelOnaga** [hgrecco/pint#1258]
https://github.com/hgrecco/pint/blob/f9d9bdee1861cc94b72acc717f3f221ad82b8f1c/pint/quantity.py#L1551
https://github.com/hgrecco/pint/blob/f9d9bdee1861cc94b72acc717f3f221ad82b8f1c/pint/quantity.py#L1552

Floating point are not precise: https://docs.python.org/3/tutorial/floatingpoint.html

This causes quantity comparisons to not work as expected (in my case I have to deal with temperature a offset measure [https://pint.readthedocs.io/en/latest/nonmult.html](url) ).

Ex:
`degree_Celsius = kelvin; offset: 273.15 = °C = celsius = degC = degreeC`
```
y = Q_(20, 'kelvin')
c_magnitude = 20-273.15  # -253.15
z = Q_(c_magnitude, 'celsius')
z.to_base_units().m # 20.0
z==y  # returns True

x = Q_(-253.15, 'celsius')
x.to_base_units().m # 19.99999999999997
z==x  # returns False
y==x  # returns False

```
Possible solution:

```
from math import isclose as float_eq
FLOAT_MARGIN = 0.0001  # this could be a registry configurable value
if self._REGISTRY.autoconvert_offset_to_baseunit: 
   return float_eq(self.to_base_units()._magnitude, other, abs_tol=FLOAT_MARGIN)
```

**Comment by jules-ch** [comment]
To be short Quantity float comparison works as expected in the same way builtin float comparison works

In your example:

```python
from pint import UnitRegistry

ureg = UnitRegistry()
Q_ = ureg.Quantity

>>> 20 - 273.15
-253.14999999999998

>>> Q_((20 - 273.15), 'celsius').m
-253.14999999999998

>>> 20 - 273.15 + 273.15
20.0

>>> (Q_((20 - 273.15), 'celsius').to_base_units()).m
20.0

>>> -253.15 + 273.15
19.99999999999997

>>> Q_(-253.15, 'celsius').to_base_units().m
19.99999999999997
```

Pint is performing these exact operations on floating type, and the result is the one expected by the user.

To answer your question we can't introduce your solution since the comparison is working as expected

```python
>>> ( 20 - 273.15 + 273.15) == (-253.15 + 273.15)
False
```

**Comment by jules-ch** [comment]
If you want to use exact Decimal type you can : 

```python
from pint import UnitRegistry
from decimal import Decimal

ureg = UnitRegistry(non_int_type=Decimal)
Q_ = ureg.Quantity


>>> Q_(Decimal("-253.15"), "celsius").to_base_units().m
Decimal('20.000')

**Comment by MarcelOnaga** [comment]
Thanks for your reply @jules-ch   

What I am expecting from pint Quantities is that since are overwriting operators the operations to work as expected.  
I have tried `UnitRegistry(non_int_type=Decimal)`, but the issue is that it still does not work.  
Decimal does not work because of the way pint typecasts registry configuration to float and not to Decimal. This causes 2 issues, first Decimal with float operations raise errors, second if configured to work from decimal config we still get to the first issue.

My second suggestion would be that if we set `ureg = UnitRegistry(non_int_type=Decimal)` then the offset and scale values should be typecasted to Decimal:
```
>>> ( decimal.Decimal(20) - decimal.Decimal(273.15) + decimal.Decimal(273.15)) == (decimal.Decimal(-253.15) + decimal.Decimal(273.15))
True
```
Could this be considered  as a solution?

**Comment by jules-ch** [comment]
You shouldn't use float in Decimal construtor use string. See the documentation https://docs.python.org/3/library/decimal.html. 
There are also some function to build from float.

In your example the Decimal is the exact representation of the float as input.

**Comment by hgrecco** [comment]
Thanks for your interest in Pint. I would like to join the conversation with a few comments.

A tolerance for the equal comparison is a slippery slope that we will not take. The meaning of equality is well-defined and adding an implicit tolerance will break this contract. As @jules-ch said, equality works as expected.

Difference arise in all calculations due to floating point error and convergence in the algorithms among others. All these should be dealt with an accessory function, just like numpy, scipy and other scientific package does.

As @jules-ch correctly pointed out you can use `Decimal` (or actually any numeric type) to deal with no ints. Indeed this means that now all the non integers in the registry are Decimals, not float. But I disagree with you that this means that Pint is `typecasting to float and not to Decimal`. Changing the `non_int_type` means that numbers are **parsed** from text using the Decimal constructor and that is why they retain the same precision (within the Decimal capabilities) that the user intended when wrote it in a text file. 

Indeed, calling `Quantity(3.2, 'meter')` will have a float magnitude because the `3.2` string is parsed into float by the python interpreter and then given to Quantity. Pint cannot do anything about that (Sidenote: AFAIK there only very few languages in which the default non int datatype for the interpreter/compiler is Decimal, due to performance reasons)

That is why @jules-ch mentions that a solution will be using a constructor from str.

**Comment by MarcelOnaga** [comment]
Thanks @hgrecco 

My first assumptions with regard to float ware wrong I agree, but when it comes to using  `non_int_type` and 'Decimal' I think pint could improve and if type casting can be considered as @jules-ch mentioned would be great!
If I can help with that let me know how, I do not have much experience with participating in public libraries...

One argument for type casting is that it feels like transforming one Quantity to another has side effects when `non_int_type` is set. 
Because config offsets and scale values are becoming floats they influence the result:
```
>>> import pint
>>> from decimal import Decimal
>>> ureg = pint.UnitRegistry()
>>> Q_ = pint.Quantity
>>> u = Q_(Decimal('-253.15'), 'celsius')
>>> y = Q_(Decimal('20'), 'kelvin')
>>> u==y
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python3.8/site-packages/pint/quantity.py", line 115, in wrapped
    return f(self, *args, **kwargs)
  File "python3.8/site-packages/pint/quantity.py", line 1564, in __eq__
    self._convert_magnitude_not_inplace(other._units),
  File "python3.8/site-packages/pint/quantity.py", line 610, in _convert_magnitude_not_inplace
    return self._REGISTRY.convert(self._magnitude, self._units, other)
  File "/site-packages/pint/registry.py", line 954, in convert
    return self._convert(value, src, dst, inplace)
  File "python3.8/site-packages/pint/registry.py", line 1840, in _convert
    return super()._convert(value, src, dst, inplace)
  File "python3.8/site-packages/pint/registry.py", line 1454, in _convert
    value = self._units[src_offset_unit].converter.to_reference(value, inplace)
  File "python3.8/site-packages/pint/converters.py", line 72, in to_reference
    value = value * self.scale + self.offset
TypeError: unsupported operand type(s) for +: 'decimal.Decimal' and 'float'
```

**Comment by hgrecco** [comment]
Repeat your example with:
```python
>>> ureg = pint.UnitRegistry(non_int_type=Decimal)
>>> Q_ = ureg.Quantity
```
and you will get that `True` for `u == y` (as expected).

The fact that casting that implicit casting from float to decimal is not possible is a decision from Python. You read the rationale in this [part of PEP 327](https://legacy.python.org/dev/peps/pep-0327/#id17)

What you have to keep in mind is that every time that you put a string representing a non integer number into the python interpreter it is parsed as a float. That is why Decimal works better when constructing a Decimal from string. That is one of the reasons that Pint uses a text file to store definitions. That is why we can only parse (not cast!) when the input is a string.

**Comment by MarcelOnaga** [comment]
Perfect! Thanks!
