### ISSUE TITLE
Precision (floating point errors) during unit conversion

### ISSUE THREAD

**Issue by gerbenoostra** [hgrecco/pint#1263]
In the following code
```
a = np.arange(20) * ureg.mps
b = a.to(ureg.km/ureg.hour)
c = np.arange(20)*3.6
```
`b.m != c`
more specifically:
`b` is `[0.0 3.5999999999999996 7.199999999999999 10.799999999999999 14.399999999999999 18.0 21.599999999999998 25.199999999999996 28.799999999999997 32.4 36.0 39.599999999999994 43.199999999999996 46.8 50.39999999999999 53.99999999999999 57.599999999999994 61.199999999999996 64.8 68.39999999999999] kilometer / hour`
while `c` is `[ 0.   3.6  7.2 10.8 14.4 18.  21.6 25.2 28.8 32.4 36.  39.6 43.2 46.8, 50.4 54.  57.6 61.2 64.8 68.4]`

I though expected the magnitude of b and c to be equal.

Is there a way to get Pint to work with full precision?

**Comment by gerbenoostra** [comment]
Note, the issue happens in `BaseRegistry`, where in method `_get_root_units` the following statements:
```
accumulators = [1, defaultdict(int)]
self._get_root_units_recurse(input_units, 1, accumulators)
```
Result in `accumulators[0]` to become `3.5999999999999996`.

**Comment by ConorSheehan1** [comment]
I get float precision errors for even simple conversions, e.g. mm -> cm

```python
import pint
ureg = pint.UnitRegistry()
(112.0 * ureg.mm).to('cm').magnitude
# 11.200000000000001
```

It looks like the initial conversion to millimeters is fine, but once I convert to centimeters, magnitude has a rounding error
```python
import pint
ureg = pint.UnitRegistry()
(112.0 * ureg.mm).magnitude
# 112.0
```

Seeing some very strange behaviour starting with an integer instead of float. It looks like the precision errors are almost random, but I get the same result every time I run it
```python
[(v * ureg.mm).to('cm').magnitude for v in range(20)]
# [0.0, 0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.1, 1.2000000000000002, 1.3, 1.4000000000000001, 1.5, 1.6, 1.7000000000000002, 1.8, 1.9000000000000001]
```

Maybe this could be solved by setting precision? https://github.com/hgrecco/pint/issues/588
Or better coercion back to float? e.g. https://github.com/hgrecco/pint/issues/1193

Tested with 
pint 0.17
python 3.6.8

**Comment by TommyHanusa** [comment]
I think I'm seeing the same issue with ml to ul.

Right now if you go to line 1095 of registry.py and change the `return value` to `return round(value,10)` it seems to fix the issue. Although I suspect this is probably the wrong way to handle this.

**Comment by jules-ch** [comment]
I'm going to close this issue. Floating point precision is inherent to how float64 datatype is handled by the computer.

If you want precision you need to use `is_close` function from the `math` module or use `Decimal` type that pint can handle.

`UnitRegistry(non_int_type=Decimal)`

Be careful not to mix Decimal registry with Float one.

**Comment by TommyHanusa** [comment]
Hey, thanks for mentioning `non_int_type=Decimal` I wasn't aware of that option.

Since it seems like people run into this issue somewhat frequently, would it be possible to make that the default behavior for UnitRegistry()? If that's not a good idea, could `non_int_type=Decimal` be mentioned in the Quickstart Tutorial or Known Issues documentation?

**Comment by jules-ch** [comment]
Yeah Documentation is non existent on this.

It won't be the default behavious though.
