### ISSUE TITLE
Give warning when using unit names that have similar names in different systems.

### ISSUE THREAD

**Issue by mmarras** [hgrecco/pint#1331]
I recently discovered the situation that `ureg.tons` are imperial, whereas, `ureg.t` are metric tons. At the time of use I was not aware of the imperial ton and my calculations were strangely off. 
Wouldn't it be helpful, if the system informs the user when he uses units that have similar names in other systems to avoid disambiguates? Should of course be opt-out possibility for more experienced users.

**Comment by teauxfu** [comment]
That is kind of ambiguous, especially when considering how other plural units are parsed
```py
assert ureg.mile == ureg.miles
```

A local workaround to get closer to your expected behavior may be to define your own unit system
https://pint.readthedocs.io/en/stable/systems.html

But it is probably easier to just conform to using the units as defined.

I dunno what a graceful way to complain/warn the user would be that wouldn't be obtuse.
I guess it depends on the context of how the particular user is using pint?

**Comment by mmarras** [comment]
Maybe we can just inform the user, about common false friends in the docs.

**Comment by hgrecco** [comment]
I agree with documenting this. I will close this issue for now. Feel free to reopen

**Comment by keewis** [comment]
would it make sense to rename `tons` to `imperial_tons`, make `tons` an alias of `t`, and to set the general rule that for naming conflicts SI is always preferred?

This would probably be a breaking change (and one we probably can't have a deprecation cycle for), but I feel it would still be an improvement.
