### ISSUE TITLE
Mixed-unit vectors and matrices

### ISSUE THREAD

**Issue by tobinjones** [hgrecco/pint#1385]
I'm working with some code that defines vectors and transformation matrices that operate on those vectors.

A simplified (2D) example is something like this:

```python
# We have a particle with a position and angle
particle = array([1, 2]) # units are ['mm', 'mrad']

# What happens if we let the particle drift through free space for 2 meters?
transfer = array([[1, 2],[0, 1]]) # units are [['','mm/mrad'],['mrad/mm','']]

# We can represent this as a matrix equation
particle_out = transfer @ particle
```
The result is `array([5, 2])`, meaning the particle now has position "5 mm" and the same angle "2 mrad". But clearly if I got the units of the "particle" wrong and used units `['m', 'deg']` then my answer would be wrong.

In the 2D case, I might just explicitly write out the matrix math, and not use vectors/arrays. However in reality I'm interested in doing this for matrices that are up to 24x24. 

Is there is any way to express this with Pint?

**Comment by jules-ch** [comment]
No I don't think you can work with mixed units, just like you cannot work with mixed dtypes with numpy.
Best way is to go back to magnitude work with numpy arrays to combine & make computations on arrays & matrix where you ensure you have the right units with functions like `to("mm")` or `m_as("mm")`.

Numpy have made some steps towards metadata inside DTypes (https://numpy.org/neps/nep-0041-improved-dtype-support.html) but even there you need to have one unit per arrays or matrix.

A custom function with `@unit.wraps` might be useful there.

**Comment by tobinjones** [comment]
Ok thank you very much for the answer, I appreciate it! I will just keep Pint "at the edges" like you suggest.

Since it feels like from your response that this is solidly out-of-scope, I'm happy for this to be closed.

**Comment by jules-ch** [comment]
Closing this

**Comment by kbauer** [comment]
Related: I came across this trying to invert a matrix with mixed units. This appears e.g. with stiffness matrices for rigid bodies, which have a 3x3 submatrix with a unit pattern (using SI units).

The force equations read

    f = K.q
    
where f, q are six-vectors of mixed dimensions (force and torque, distance and angle), resulting in an overall pattern (using SI units Newton, meters, seconds)

     N       N/m  N/m  N/m   N    N    N      m
     N       N/m  N/m  N/m   N    N    N      m
     N    =  N/m  N/m  N/m   N    N    N   =  m
    N.m       N    N    N   N.m  N.m  N.m     1
    N.m       N    N    N   N.m  N.m  N.m     1
    N.m       N    N    N   N.m  N.m  N.m     1

For inverting, being unable to store units this way and perform operations on them, leads to significant added complexity *or* loss of the tracking of units of the properties. Mostly it means having to do the “units math” by hand.

(Side remark: Also ties in a bit to #1288, due to the question of what of these terms should have “rad” added, when being explicit about it, which when done badly could even make the matrix uninvertible due to the units, I think.)
