### ISSUE TITLE
Question: Is there a safe approach for incompatible but dimensional-identical units? 

### ISSUE THREAD

**Issue by jmrgibson** [hgrecco/pint#1388]
I have two measurements of frequency (revolutions / minute), related by a dimensionless gear ratio. Does pint have a good way of handling conversion between the two?

I know I can define `input_gear_radians` and `output_gear_radians` as separate units, but I'm wondering if there is a good way of enforcing the use of a gear ratio constant when converting between the two. I thought I could use `contexts`, but since `contexts` only operates on dimensions, not units, it doesn't seem to have any effect when defining a conversion where the input and output dimension are the same. 

Thanks

**Comment by jules-ch** [comment]
IMO you should use a custom function that takes the input angular frequency (rpm) & gear ratio to compute the output angular frequency.

Does this suit your needs, or do you have an example to share.

**Comment by cpascual** [comment]
@jmrgibson : in which sense do you say that the units are incompatible? 

I may be missing some key point, but I would say that the *units* are compatible: it is the involved *quantities*  (e.g. `input_gear_frequency` and `output_gear_frequency`) the ones that are related via the `gear_ratio` constant, but not their units (both should be `"rpm"`)

Therefore, instead of trying to convert the between the gear frequencies via pint unit conversions, I think that you should just apply the gear ratio to the quantities (as @jules-ch  suggests)

**Comment by jmrgibson** [comment]
Yeah, I think that will be the approach I take. In a statically typed language, I would have created separate types for `input_gear` and `output_gear`, and then the compiler would prevent me using one where the other should be used (and the provide a conversion method that takes the gear ratio parameter. 

Thanks all

**Comment by hgrecco** [comment]
While I agree with @cpascual in this case, I would like to comment that there is the notion of role that we have proposed for other problems. We have never implemented but I think it could be useful in some cases. #551
