### ISSUE TITLE
Support for normalization

### ISSUE THREAD

**Issue by infraredgirl** [hgrecco/pint#151]
It would be nice to have support for conversion of values to the human readable/normalized form. Let me explain what I mean by giving a few examples.

```python
>>> normalize(1, 'B')
(1, 'B')
>>> normalize(1024, 'B')
(1, 'KB')
>>> normalize(10*1024**3, 'B')
(10, 'GB')
>>> normalize(0.5, 'MB')
(512, 'KB')
>>> normalize(60, 's')
(1, 'min')
>>> normalize(0.5, 'day')
(12, 'hr')
```
You get the idea. I think this kind of utility function would be extremely useful. (If this is already supported, and I have just missed it, please do let me know.) Thanks for considering this!

**Comment by ryanpdwyer** [comment]
Here is a functional implementation for the standard SI prefixes.

https://gist.github.com/ryanpdwyer/bcb4dc3d2a2a6b6734bb

**Comment by hgrecco** [comment]
I was toying with the idea to get a compact representation in #15. It basically used and OrthogonalMatchingPursuit to find the shortest combination of units (base and derived) with the same dimensionality of the input units. It was working for some cases, but not giving good results in some cases. 

I like @ryanpdwyer because it is like a *guided* compact methods. And then we might work on the infer_base_unit in a second step. Lets merge it **after** we finish with the _systems branch and #202.

**Comment by hgrecco** [comment]
I am closing this now. Feel free to reopen.
