### ISSUE TITLE
0.19 breaks scientific notation in `siunitx` formatter.

### ISSUE THREAD

**Issue by CD3** [hgrecco/pint#1515]
I have not looked at the code yet, but `siunitx` formatter is putting `times 10^{...}` inside `SI{...}{...}` when `e` is used. Here is a sample script
```
import pint

ureg = pint.UnitRegistry()

print("{:Lx}".format(ureg.Quantity(0.1,'m')))
print("{:L}".format(ureg.Quantity(0.1,'m')))
print("{:eLx}".format(ureg.Quantity(0.1,'m')))
print("{:eL}".format(ureg.Quantity(0.1,'m')))
print("{:e}".format(ureg.Quantity(0.1,'m')))
```
with `0.18` this gives
```
\SI[]{0.1}{\meter}
0.1\ \mathrm{meter}
\SI[]{1.000000e-01}{\meter}
1.000000\times 10^{-1}\ \mathrm{meter}
1.000000e-01 meter
```
for `0.19` it gives
```
\SI[]{0.1}{\meter}
0.1\ \mathrm{meter}
\SI[]{1.000000\times 10^{-1}}{\meter}       <<< This is the issue
1.000000\times 10^{-1}\ \mathrm{meter}
1.000000e-01 meter
```
The `siunitx` package expects `e` notation and handles formatting the scientific notation itself.

**Comment by jules-ch** [comment]
Changes comes from this commit ff15a1483b3b823bb35866436e084ba07a408377

**Comment by jules-ch** [comment]
@keewis any idea ?

**Comment by CD3** [comment]
The line were the exponent gets expanded to `\times ...` is here:
https://github.com/hgrecco/pint/commit/ff15a1483b3b823bb35866436e084ba07a408377#r72883962

There is a check for 'L' in the uspec, but it should only be expanded if there is also not an 'x' modifier present.

cdclark

**Comment by keewis** [comment]
thanks for investigating, it does indeed sound like that's the issue (although I'm somewhat surprised that changing `spec` to `uspec` caused a change in behavior). We're using `in` to check for the presence of a formatter, but that fails if one formatter is a substring of another. 

To fix this, I think we should try to properly separate modifiers from formatters and compare full strings. With that, that line would become
```python
if unit_formatter == "L":
```

In the long term we might want to convert `"L"` and `"H"` to `Quantity` formatters, since they work on both magnitude and unit (we'd first need to figure out what `Quantity` formatters are, though)

**Comment by jules-ch** [comment]
I'm trusting you guys on the matter, I don't know much on this part of the code. Can any of you @keewis or @CD3, draft a PR ?

**Comment by CD3** [comment]
I probably can't look at it for a few week, we have finals starting soon, but I'll look into it after. I agree, about spec -> uspec causing the problem, that might not be the actual problem, I just saw it when I was skimming the commit.
