### ISSUE TITLE
rpm to Hz issue

### ISSUE THREAD

**Issue by AndreyNvk** [hgrecco/pint#1540]
`Pint==0.19.2`

Expecting 60 rpm to be 1 Hz, but getting strange results:

```
Python 3.8.13 (default, Apr 19 2022, 02:32:06) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pint import UnitRegistry
>>> ureg = UnitRegistry()
>>> frequency = ureg('60rpm')
>>> frequency.to('Hz')
<Quantity(6.28318531, 'hertz')>
```

`revolution` [here](https://github.com/hgrecco/pint/blob/master/pint/default_en.txt#L224) links to the [line](https://github.com/hgrecco/pint/blob/master/pint/default_en.txt#L128) where it is equal to `2 * pi` which leads to the statement like `Hz = rpm * 2 * pi / 60` instead of `Hz = rpm / 60`

**Comment by OrangeChannel** [comment]
You're probably looking for revolutions / sec. It's much more useful in (SI) physics for Hz to imply rad/s. Revolutions are not the non-dimensional base unit, but you could probably use a context to alter this? Someone with more experience with contexts might be able to help.

**Comment by jules-ch** [comment]
Issue has been raised and there is no clear path using context, since context are used to convert from & to different dimensions.

I'm quoting the SI BIPM Brochure (Bureau International des Poids et Mesures):

> The SI unit of frequency is hertz, the SI unit of angular velocity and angular frequency is
radian per second, and the SI unit of activity is becquerel, implying counts per second.
Although it is formally correct to write all three of these units as the reciprocal second, the
use of the different names emphasizes the different nature of the quantities concerned. It is
especially important to carefully distinguish frequencies from angular frequencies, because
by definition their numerical values differ by a factor1 of 2π. Ignoring this fact may cause
an error of 2π. Note that in some countries, frequency values are conventionally expressed
using “cycle/s” or “cps” instead of the SI unit Hz, although “cycle” and “cps” are not units
in the SI. Note also that it is common, although not recommended, to use the term
frequency for quantities expressed in rad/s. Because of this, it is recommended that
quantities called “frequency”, “angular frequency”, and “angular velocity” always be given
explicit units of Hz or rad/s and not s−1
.


That's why you're getting this results, we have not taken any action because Hz should only be applied to frequency, not angular frequency. `rad/s` & `rpm` should be the prefered units.

xref : #1288

We need to add a warning since it's becoming a common misunderstanding regarding the use of Hz vs `rad/s` or `revolution/s`
