### ISSUE TITLE
Wrong delta from float quantities

### ISSUE THREAD

**Issue by vnpro** [hgrecco/pint#1690]
Delta from float quantities seems wrong

Pint 0.20.1

sample code:
```
from pint import UnitRegistry


ureg = UnitRegistry()

def  tos(quantity:float): return ureg.Quantity(quantity, ureg.second)
def toms(quantity:float): return ureg.Quantity(quantity, ureg.millisecond)
def toµs(quantity:float): return ureg.Quantity(quantity, ureg.microsecond)

print(tos(0.543) - tos(0.542))
print(tos(0.543) - tos(0.541))
print(tos(0.543) - tos(0.540))
print(tos(0.005) - tos(0.005))

print(toms(0.225) - toms(0.224))
print(toms(1.451) - toms(1.450))

print(toµs(1.451) - toµs(1.450))
print(toµs(0.5) - toµs(0.2))
print(toµs(0.05) - toµs(0.02))
```

results:
```
0.0010000000000000009 second
0.0020000000000000018 second
0.0030000000000000027 second
0.0 second
0.0010000000000000009 millisecond
0.001000000000000112 millisecond
0.001000000000000112 microsecond
0.3 microsecond
0.030000000000000002 microsecond
```

**Comment by jules-ch** [comment]
Everything looks good to me, what did you expect  as a result?

**Comment by keewis** [comment]
I get the exactly same results with standard python floats (minus the units, of course), so what you're seeing is caused by the nature of floats: trying to represent an infinite number of real values with a finite number of bits: you get small rounding errors.

If you're looking for more accurate results, you might want to look into the standard library `fractions` and `decimal` modules. To use them with `pint`, create the registry with e.g. `UnitRegistry(non_int_type=decimal.Decimal)`.
