### ISSUE TITLE
Quantity class is instance of Iterable, but is actually not iterable

### ISSUE THREAD

**Issue by DirkdenHoedt** [hgrecco/pint#1719]
I'm using the DeepDiff library to compare two dictionaries to each other, these dictionaries contain Quantity classes from Pint. DeepDiff checks if the Quantity class is instance of Iterable, which it is. But when it then tries to iterate over the Quantity object, `TypeError: 'float' object is not iterable` is thrown. How could this issue be fixed?

**Comment by burnpanck** [comment]
This has come up before: #1337. Strictly speaking, the behaviour of Quantity is ok: it implements `__iter__`, so it is iterable. Even if `__iter__` actually always fails. However, in the wild, this has cause issues before, e.g. in relation to the integration into pandas through `pint_pandas`, which struggles with performance issues because pint falls back to object mode. I believe some of those issues have been resolved by patching pint itself, which would also be an option here: Patch DeepDiff to not just do an instance check, but check if `__iter__` is successful.

However, I am of the firm belief that a better solution would be to make a distinction between scalars and arrays, see #1128 (shameless plug to my previous pitch to re-investigate that).

**Comment by hgrecco** [comment]
@burnpanck Lets make a decision about scalar and arrays for 0.23 and implement it. If the pint-pandas community agree, I would almost certainly agree.

**Comment by Evidlo** [comment]
I see this was closed, but I'm getting the same behavior as before when checking if the quantity is of instance `abc.Iterable`.  Was this addressed in a particular commit?

For context, I'm using pint in a library for performing 3D tomography and it fails [here](https://github.com/ahendriksen/tomosipo/blob/master/tomosipo/types.py#L70).

**Comment by burnpanck** [comment]
The short answer is "no, it has not been addressed" - because technically, this is not an issue of pint and any direct addressing of this would be just a hack bound to break again. According to the [doc of `abc.Iterable`](https://docs.python.org/3/library/collections.abc.html?highlight=iterable#collections.abc.Iterable), checking `isinstance(obj, abc.Iterable)` does not imply that iterating the object actually succeeds. They explicitly state the only reliable way to check for iterability of an object is to try to call `iter(obj)`.

That said, `pint` could make an effort to support that use-case better, and IMHO the best way would be to create distinct types for `QuantityScalar` (not iterable) and `QuantityArray`, which would have many other implications. That change however is non-trivial, and while there has been an unsuccessful attempt at implementing it a long time ago, there is no current effort that I'm aware of (I'm no maintainer on this project though). It seems that consent on the effort is likely, but probably a champion is required to actually implement it.
