### ISSUE TITLE
Latex Output for Temp Uses \textdegree (Which Is Invalid In Math Mode)

### ISSUE THREAD

**Issue by StresseJesse** [hgrecco/pint#1726]
Hi!

I am SO sorry if I am missing something. I really tried to sort this out (but "pint" is already hard for Google to handle and latex-specific pint troubleshooting proved a bit more difficult than usual).

Thank you SO much for this AMAZING tool, by the way!! It honestly blows me away.

Okay, so my issue comes up when I am inserting the output into Latex.

```from pint import UnitRegistry
ureg = UnitRegistry(autoconvert_offset_to_baseunit = True)
ureg.default_format = '~L.4g'
t = ureg('30 degC')
print(t)
>>> 30\ \mathrm{°C}
```

That `30\ \mathrm{°C}` is interpreted by Latex as `30\ \mathrm{\textdegree C}` which throws an error and doesn't display correctly because "\textdegree" isn't valid in math mode.

I think this should be a fairly simple fix, since I think the proper syntax should just be `^{\circ}C`

**Comment by cgevans** [comment]
The problem here is that LaTeX has very inconsistent and often poor handling of unicode, which heavily depends on what you're actually using.   The following produces a degree only for the first ° on a modern `latex` or `pdflatex`, because, as you point out, it translates it to \textdegree, which is invalid in math mode.   It also only produces the first degree in `xelatex` or `lualatex`, but not because of a translation, but because the symbol is missing in the font used:

```latex
\documentclass{article}
\begin{document}
A text °C, and a math $°C$.
\end{document}
```

If you add `\usepackage{unicode-math}`, then xelatex and lualatex work, and produce both degrees, but pdflatex and latex fail entirely, because they don't support unicode-math.   This is also the case if you add `\usepackage{fontspec}`, even if you don't actually specify another font.

Having pint output `$^{\circ}C$` would be problematic because the output would, instead, fail in text mode.  I'm inclined to say that it makes the most sense to keep xelatex/lualatex-compatible output, as it looks cleaner and is more likely to work.

**Comment by hgrecco** [comment]
I agree with @cgevans. In any case, I will be moving the Formatting part to a "delegate" to favour composition over inheritance. Hopefully, this allows anybody to easy build new formatters or hack existing ones.
