### ISSUE TITLE
Support *args and **kwargs in wraps

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint#196]
In order to support more functions with `wraps`, add the ability to support args and kwargs.
1. API (See #195)
2. Provide use cases
3. How shall we distinguish if the return value is just applying the same operation to all inputs (e.g. rescale) or sumarizing (e.g. sum). This is important to see how we put units.

**Comment by mikofski** [comment]
In addition, it might also be helpful to specify `args

**Comment by techdragon** [comment]
I've had a lot of trouble with the wraps function being easy to make mistakes with due to the arguments, ordering etc. Having a 'more explicit' mode that allowed me to specify the keyword arguments that I want to wrap, would be great. It would also solve the issue of being unable to have both "wrapped" + normal arguments (which I come across whenever I am working with databases of physical and/or chemical properties and code libraries that works with these sorts of databases)

This issue actually feels like something that should be solved with the recently added support for type annotations. Something like one of the following would feel really natural to me.

```python
import pint
si = pint.UnitRegistry()

@si.wraps()
def speed(distance: si.meters, time: si.seconds):
    return distance / time
```

Alternatively, exposing dimensions in the type hierarchy and somewhere in the library so that they can be imported and used by the type annotations.

```python
import pint
si = pint.UnitRegistry()

@si.wraps()
def speed(distance: pint.dimensions.distance, time: pint.dimensions.time):
    return distance / time 
```

Or alternatively, if the dimensions were exposed on the UnitRegistry...

```python
import pint
si = pint.UnitRegistry()

@si.wraps()
def speed(distance: si.dimensions.distance, time: si.dimensions.time):
    return distance / time 
```

But this doesn't feel quite right to me since dimensions are more universal than units. Regardless, this may just be something that the library can't quite handle since this sort of type check based approach does is completely different to how it currently works, and probably belongs in as its own Issue.

**Comment by techdragon** [comment]
@hgrecco While I'm not sure how to do the args and kwargs here, I'm familiar enough with types and signatures that I'm going to tinker with them in some of my own code ( I would have tried to use them for this code anyway 😃 ) and now I know you're not opposed to integrating type and type signature related features I'll be sure to make a pull request if I manage to come up with anything that seems good enough others could rely on it.

**Comment by hgrecco** [comment]
Great!

**Comment by mikofski** [comment]
Any comments on why this issue is closed? Too old, out of scope, won't fix, or has it been addressed in a recent PR? Thanks!

**Comment by hgrecco** [comment]
The stability of `wraps` was greatly improved when implementing default values in July 2018. So, I think we need to use the current master as new base to define better what we want to implement next. (i.e. write a few test cases)

**Comment by hgrecco** [comment]
For example, now we can access the signature of the wrapped function.
