### ISSUE TITLE
pint 0.24 / numpy 2.0 / python 3.9 issues

### ISSUE THREAD

**Issue by keewis** [hgrecco/pint#1974]
`numpy>=2` will include a couple of breaking changes (to be released soonish), so it would be good to have a release of `pint` before that (I'd also love to have #1922 in a release, as it will fix some typing issues on `python>=3.12`)

Most of the urgent issues have already been fixed, the only thing left is #1971.

Other than that, `__array__` has gained a optional `copy` kwarg which we should add (the version of `__array__` without `copy` will cause a deprecation warning).

**Comment by cmutel** [comment]
In case anyone is having weird pint errors, or getting this error:

```python
AttributeError: module 'numpy' has no attribute 'cumproduct'. Did you mean: 'cumprod'?
```

It's because you installed Numpy 2.0.RC1, which isn't yet supported.

**Comment by andrewgsavage** [comment]
I'm not sure how best to handle the `__array__(copy)` issue, we don't handle other optional args at present. 
Other than that seems like 2.0 works now - I've added it to the matrix.(maybe too a bit too many places)

**Comment by andrewgsavage** [comment]
I think #1978 and #1960 could be merged if someone has the time to review. 

Otherwise I think we're ready for a new release. Are there any other PRs that could be merged?

**Comment by keewis** [comment]
I would forward `copy` to the wrapped array, but in any case this is not urgent, since not having that argument will warn, not raise.

#1960 is a documentation-only PR (and from a quick glance I can't see anything wrong), so I think that PR is fine?

**Comment by dopplershift** [comment]
We're officially on the clock here, as NumPy 2.0 will release [16 June 2024](https://github.com/numpy/numpy/issues/24300#issuecomment-2125643448).

It would be good to get some kind of release out the door since currently importing pint with numpy 2 installed results in the `AttributeError` noted above.

I'm going to update on conda-forge to add a constraint for numpy < 2.

**Comment by jakirkham** [comment]
Do we know what issues still remain here?

Curious if anyone has tried to run the test suite with NumPy 2. If so, would be curious to know what that reveals

**Comment by andrewgsavage** [comment]
> We're officially on the clock here, as NumPy 2.0 will release [16 June 2024](https://github.com/numpy/numpy/issues/24300#issuecomment-2125643448).
> 


I've released a pre-release. We've said to leave a week before full release so 0.24 can be released on the 8th.

**Comment by andrewgsavage** [comment]
0.24 released

**Comment by jakirkham** [comment]
Thanks Andrew! 🙏

**Comment by takluyver** [comment]
If anyone else is still seeing the `no attribute 'cumproduct'` error, note that NumPy 2.0 is compatible with Python 3.9 and up, but Pint 1.24 requires Python 3.10 or above. So unfortunately, `pip install numpy pint` on Python 3.9 results in pint not being importable at all.

**Comment by slokhorst** [comment]
> If anyone else is still seeing the `no attribute 'cumproduct'` error, note that NumPy 2.0 is compatible with Python 3.9 and up, but Pint 0.24 requires Python 3.10 or above. So unfortunately, `pip install numpy pint` on Python 3.9 results in pint not being importable at all.

This is an issue on Ubuntu 22.04. 

Would it be possible to tag a new point release `0.23.1`, with:
`requires-python = ">=3.9"` and `numpy = "^1.23"`?

**Comment by takluyver** [comment]
Unfortunately I don't think that a new point release with metadata saying it needs numpy 1.x really solves this, because the dependency resolver is still free to pick pint 0.23, which appears to the tools to be compatible with numpy 2.0. In some cases it might decide to downgrade numpy instead, but not reliably.

Further complicating it, numpy is an optional dependency of pint. So if you `pip install pint[numpy]`, pip would try to get compatible versions, but `pip install pint numpy` will install them as separate packages, ignoring any version constraints. There's no way to specify "pint doesn't require numpy, but numpy 2.0 breaks it" in packaging metadata.

The possible fixes I'm aware of here are:

- Downstream packages drop support for Python 3.9 entirely.
- Downstream packages require Numpy 1.x for Python 3.9 (`numpy <2; python_version < "3.10"`)
- Pint makes a new release that's compatible with both Python 3.9 and Numpy 2.0. I think this ought to be easy in principle - it's only been a few months since Pint dropped 3.9 support - but I spent a while on it, and unfortunately neither undoing the 3.9 changes nor redoing the numpy changes was straightforward.

**Comment by andrewgsavage** [comment]
> * Pint makes a new release that's compatible with both Python 3.9 and Numpy 2.0. I think this ought to be easy in principle - it's only been a few months since Pint dropped 3.9 support - but I spent a while on it, and unfortunately neither undoing the 3.9 changes nor redoing the numpy changes was straightforward.

I'm not opposed to this. Was this https://github.com/takluyver/pint/tree/0.23-np-2.0 what you tried? Did you look at making 0.24 work with 3.9?

**Comment by takluyver** [comment]
Thanks, that would be great! That was the branch I was trying on, working
forwards from the 0.23 tag and trying to cherry pick the necessary changes.

I tried working backwards from 0.24 first, but quickly got conflicts as I
reverted commits, so I switched the approach. I didn't get far enough to
push that. But I now suspect that was the better plan after all.

I'm away from my computer for a few days, but I can look into this again
next week if no-one else tackles it.

**Comment by andrewgsavage** [comment]
I've got 0.24 working with py39 https://github.com/hgrecco/pint/pull/2019 so I'll make 0.24.1 available for py39.
some seemingly unrelated failures though...

**Comment by takluyver** [comment]
Thanks! Yes, looking at the diff, that was much easier than what I was
trying

**Comment by andrewgsavage** [comment]
I think the all PRs needed to fix issues for 0.24.1 are now merged. would be good to confirm the babel issue #2006

**Comment by andrewgsavage** [comment]
0.24.1 released

**Comment by takluyver** [comment]
Thanks @andrewgsavage !
