### ISSUE TITLE
Shorter forms for magnitude and units

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pint#234]
`magnitude` and `units` names are clear and unambiguous names for the corresponding properties. But in certain cases, the code using them becomes really long. Here we suggest to have `m` and `u` as **abbreviated aliases** for `magnitude` and `units`. This will also help for #227.

This is similar to how `uncertainties` does it where you can use `n` for `nominal_value` and `s` for `std_dev`

Comments?

**Comment by jdreaver** [comment]
+1 from me. I think very short abbreviations like this are fine if there are only very few of them, and they are used very often. In the case of pint, extracting the magnitudes and units fits both of these criteria. Plus, users are free to use the longer names if they want to be more explicit.

**Comment by natezb** [comment]
I've always wanted to use `mag` as shorthand since `magnitude` is so long. It shortens the name while retaining legibility. However, if you do want to abbreviate `units` as well, symmetry probably suggests using `m` and `u`.

In a perfect world, I'd use `mag` for the longhand and `m` for shorthand, but it's probably too late to move away from `magnitude`.
