### ISSUE TITLE
List of units and constants in documentation?

### ISSUE THREAD

**Issue by scott-maddox** [hgrecco/pint#255]
I would love to make better use of Pint, but the documentation is sorely lacking. Where is the list of available units and constants? Is there a way to print them out in a console? If so, why isn't it mentioned in the documentation?

**Comment by hgrecco** [comment]
Thanks for your interest in Pint. I hope you find it useful.

The available units are not listed in the docs because most of the times it just works. You only need to provide the name of the unit and you get the quantity. That's all!. If the unit name is unknown you will get a nice error message.

But in case you want the list, you can find it [here (https://github.com/hgrecco/pint/blob/master/pint/default_en.txt)

Regarding the docs, I think that "sorely lacking" is a bit too harsh. The docs has a tutorial and explains each feature in a comprehensive way. It is not just a list of API, but shows examples and discuss use cases. This doesn't mean we consider it perfect. There are thing that could be improved (for example adding a link to the `default_en.txt`. And we accept pull requests!

**Comment by scott-maddox** [comment]
Thanks for the quick response, Hernan. I apologize for my poor choice of words. I had been awake for far too many hours when I wrote that.

I find the package extremely useful. Thank you.

**Comment by hgrecco** [comment]
No hard feelings! Jut let us know how we can help and feel welcomed to contribute.

**Comment by hgrecco** [comment]
Fixed in develop. Thanks.
