### ISSUE TITLE
Unit support for np.dot()

### ISSUE THREAD

**Issue by japborst** [hgrecco/pint#264]
It would be very nice to have unit support for dot products as well. Tried and experimented by adding `dot` to `__copy_units` in [quantity:857](https://github.com/hgrecco/pint/blob/master/pint/quantity.py#L857), but that was probably too easy ;)

**Comment by hgrecco** [comment]
It would be nice indeed. I think that the problem is that np.dot is handled directly by numpy in a way which is not dispatched to the object (it is not a ufunc). I would really like to support this and other but I think is not possible until we derive a Quantity directly `ndarray` and event then it is not sure that it will work. One of the main problems is explained here: https://github.com/numpy/numpy/issues/4072

**Comment by iamthad** [comment]
If the arrays have consistent units, the following seems to work:

`@units.wraps('=A*B', ('=A', '=B'))
def dot(a, b, *args, **kwargs):
    return numpy.dot(a, b, *args, **kwargs)
`

**Comment by hgrecco** [comment]
Yes! This is one of the reasons we worked on #195 (And I think the final API is much nicer!) It is good to see people making use of it. Please let me know any comments that you might have while using it.
