### ISSUE TITLE
Resolving common names(, or not)

### ISSUE THREAD

**Issue by JNRowe** [hgrecco/pint#27]
It would be nice if there was on option to retain the given name when defining units.

Specifically, it would be nice if you could define distances in metric units without them being "corrected" to the US-only spelling of metre.

Such an option would also be make it far simpler(IMO) to work with abbreviated names.  You could just use `ureg.km/ureg.h` in definitions and `%s` to display, instead of having to use the `~` modifier in all your display code.

Thanks,

James

---

While I have your attention I'm curious where the `work_year` definition comes from, and I can't seem to find a definition with Google.  Any hints?

**Comment by tmerten** [comment]
Hey there, i stumpled upon this issue and I think the discussion went away from the original request.

> it would be nice if there was on option to retain the given name when defining units.

I am finding myself in a use case where I would like to use pint to store quantities and would like to represent the unit with the "given name", so that I can store and retrieve it in the same form it was originally defined. However, as soon as I instantiate something like `q = ureg.Quantity(5, 'm')`, I am loosing the - say - users preferred unit, which is `'m'` and can retrieve only `'meter'` from pint.

Maybe I missed a way to do this and it is implemented somewhere 😕. But if it is not, I guess it would be a (hopefully rather easy and) great enhancement if pint stores this "user preference for a unit name". This way one could accesss something like `[a_quantity_instance|a_unit_instance].given_name()` (well the function name leaves room for improvement).

If you would merge something like this I can give it a try...

**Comment by hgrecco** [comment]
Indeed units are normalized to the main name as given by the registry as soon as the Quantity is created. This is good because it fails early if a unit is not defined or ambiguous, it speeds up conversions and allows to better cache results. 

Having said that, it would be nice to have a way to keep what the used have chosen. It is easy for single units. But doing it for compound units might be trickier. If you can provide a good API and internal logic, I will be have to move forward with this.

**Comment by hgrecco** [comment]
We have a way to add alias and babel is now an option.
