### ISSUE TITLE
Current Measruement/Uncertainties issues

### ISSUE THREAD

**Issue by alexfeld** [hgrecco/pint#348]
This issue is an attempt to note all of the current issues with the Measurement class and it's implementation of the uncertainties package as currently implemented in pint.
1. As noted in #278, the ordering of Quantity and Measurement objects affects the type of the returned object
2. numpy functions cause an in-place change of the type of object from measurement to a numpy ndarray with a Quantity object as the solve data member

``` python
>>>x = Quantity(1.0, 'foot')
>>>x.mean
<functools.partial at ...>
>>>x.mean()
1.0

>>>x.std
<functools.partial at ...>
>>>x.std()
0.0
>>>x
<Quantity(1.0, 'foot')>

>>>y = Measurement(1.0, 0.01, 'foot')
>>>y.mean
<functools.partial at ...>
>>>y
AttributeError: 'numpy.ndarray object has no attributed 'nominal_value'
>>>type(y)
pint.unit.Measurement
>>>m.magnitude
array(1.0+/-0.01, dtype=object)
```

The above behavior happens with other functions such as numpy.asarray as well. This makes using the objects no longer intuitive.

I'm sure I've forgotten other issues, but these are the two most problematic in my opinion.

**Comment by CD3** [comment]
I have ran into an issue with Measurements and non-multiplicative units (temperature). The following is possible with multiplicative units:
```
val = ureg.Quantity(1,'m')
unc = ureg.Quantity(1,'ft')

x = ureg.Measurement( val, unc )

print x

<Measurement(1.00, 0.3, meter)> 
```
which is convenient (this particular case is contrived and not necessarily useful). But the same is not possible with temperatures:
```
val = ureg.Quantity(100,'degC')
unc = ureg.Quantity(1,'degF')

T = ureg.Measurement( val, unc )

print T

...
Errors
...
NegativeStdDev: The standard deviation cannot be negative
```
The problem is that 1 degF gets converted to -17 degC before being set as the uncertainty. If we switch degF and degC, it works (sort of):
```
val = ureg.Quantity(100,'degF')
unc = ureg.Quantity(1,'degC')

T = ureg.Measurement( val, unc )

print T

<Measurement(100.00, 33.80, degF)>
```
This is not what would be expected, we would expect this to be 100 +/- 1.8 degF. The problem is that the uncertainty in a temperature should not be a temperature in the `pint` framework. The uncertainty in a temperature should be a `delta_*` unit because it's a difference in temperatures. But this doesn't work either:
```
val = ureg.Quantity(100,'degF')
unc = ureg.Quantity(1,'delta_degC')

T = ureg.Measurement( val, unc )

print T

...
Errors
...
NegativeStdDev: The standard deviation cannot be negative
```
The problem here is that 1 delta_degC gets converted into -457.9 degF. The issue also arises when trying to add an uncertainty to its nominal value

```
x = ureg.Measurement(100,1,'cm')
x.value + x.error # OK, this will be 101 cm

T = ureg.Measurement(100,1,'degC')
T.value + T.error # ERROR: throws an OffsetUnitCalculusError error
```
A temperature uncertainty cannot be added to its nominal value. Again, the problem is that a temperature uncertainty should be a `delta_*` unit.

The `Measurement` class supports specifying the uncertainty in a different unit than the nominal value through the constructor, but internally it stores them in the same unit. So in the case of a temperature, the uncertainty will always be converted to a non-delta unit.

I think the solution is to store both the nominal value and uncertainty as quantities and just check that the quantities are dimensionally the same.

**Comment by hgrecco** [comment]
See #350
