### ISSUE TITLE
Inconsistent equality testing

### ISSUE THREAD

**Issue by avirshup** [hgrecco/pint#383]
Quantities with different but compatible units can apparently never compare as equal (e.g., 1000 meters will never be equal to 1 km). Is this the expected behavior? `__ge__` and `__le__` behave as expected, so I've ended up with some situations where `x<=y` and `x>=y` but `x!=y`

**Example**

``` python
>>> import pint
>>> ureg = pint.UnitRegistry()
>>> q1 = 10.0 * ureg.angstrom
>>> q2 = 1.0 * ureg.nanometer

>>> q1 >= q2
True
>>> q1 <= q2
True
>>> q1 == q2
False  # I'd expect this to be True
```

I'd be happy to submit a PR for this.

**Comment by hgrecco** [comment]
Sorry for coming back so late. This is a rounding a problem. Notice that:
```
>>> q2 == q1
True
```

The rounding error comes from:
```
>>> ureg._get_root_units(q1.units/q2.units)
(0.09999999999999999, <UnitsContainer({})>)
```
because:
```
>>> 1e-10/1e-09
0.09999999999999999
```
I would be happy to fix this if there was an efficient way to deal with this.

**Comment by lamorton** [comment]
I think it is poor form in general to test whether two floats are equal, so maybe this is not such a problem. At any rate, in my opinion, it would be safest not to compare quantities that are not in the same units (including prefixes) although I can see this being something of a pain.  The advantage is that it would force the **user** to decide whether to convert q1 to q2's units or vice versa, instead of having some internal default based on ordering (say, always converting the second quantity to the same units as the first) that might surprise people who expect symmetry under the interchange of q1 and q2 but don't necessarily obtain it (rounding could work out differently, causing q1 == q2 to be true, but q2 == q1 to be false).

**Comment by hgrecco** [comment]
Closing. Feel free to reopen. As @lamorton mentioned, this is a poor  form to test for floats.

**Comment by keewis** [comment]
@hgrecco, this was not actually closed?

**Comment by jules-ch** [comment]
Closing
