### ISSUE TITLE
Is it possible to disable unit simplification?

### ISSUE THREAD

**Issue by Maher4Ever** [hgrecco/pint#389]
Hello,

I have a quantity that is measured as `force / length^2 / length`. It's important not to simplify this dimension to `force / length^3`. While calculating it's irrelevant of course, but I need to be able to display the quantity in the same dimension it was defined. Is it possible to retain this information with Pint? I already tried using brackets but to no avail.

**Comment by hgrecco** [comment]
The only way to avoid this is by using different length units. I am closing this. Please feel free to reopen or open another if there is any question.

**Comment by Ricyteach** [comment]
I have to say this is a shame. 

I posted [the Q below](https://stackoverflow.com/questions/56980495/prevent-simplification-of-units-in-pint) on stackoverflow, which I think provides clear real world examples why it would be very helpful to provide a way to customize display of units.

----------------

I sometimes use the [`pint` library][1] to display civil engineering calculations.

For these calculations, there are times when I want a quantity displayed a certain way in order to make it clear what the quantity represents. But when using `pint`, the units get automatically reduced, making things less clear.

Some examples:

 - "moment per unit length": changed from `kip·ft/ft` to `kip`
 - "area per unit length": changed from `in²/in` to `in`
 - "moment of inertia per length": changed from `in⁴/in` to `in³`
 - "slope": changed from `in/in` to unitless

Code illustrating the first example:

```
>>> import pint
>>> u = pint.UnitRegistry(system='US')
>>> x = 100*u.kip*u.ft/u.ft
>>> f'{x:~P}'
'100.0 kip'
```

How can I prevent this unit simplification, and get the units to display the way I want?


  [1]: https://pint.readthedocs.io/

**Comment by hgrecco** [comment]
There was an idea to implement something that was called "role" See #551 for a brief discussion
