### ISSUE TITLE
Advanced unit and unit group access in Pint.

### ISSUE THREAD

**Issue by elkeschaper** [hgrecco/pint#402]
Hi there,

two questions regarding pint:
First, is it possible to get a list of all possibly recognizable units? E.g., in this way, I can access all base units:
```
import pint
ureg = pint.UnitRegistry(system='mks')
dir(ureg.sys.mks)
```
What can I do to get a list that, for example, not only includes `meter` but also `nanometer` and `kilometer` ?

Second, in the current `https://github.com/hgrecco/pint/blob/master/pint/default_en.txt` list, we see that unit groups (such as length) are defined for units (such as meter, angstrom). For example,
```
# reference
meter = [length] = m = metre
```

How is it possible to access the unit group for a given unit? 
How is it possible to access all units for a given unit group?
(You may call unit groups differently internally?)

Thanks a lot! And thanks for a great library!

Elke

**Comment by hgrecco** [comment]
1) Prefixes in pint are universal (e.g. you can do nanoinch if you want). This means that any prefix can be combined with any unit so you can build them yourself. 
(There is no public API to list all prefixes at the moment, you have to access the internal `_prefixes` dict)
```python
import itertools
for prefix, unit in itertools.product(ureg._prefixes.keys(), dir(ureg.sys.mks)):
   print( prefix + unit )
```

2) In order to get all the units compatible with certain dimensionality you can do 
```
ureg.get_compatible_units('[length]')
```
or 
```
ureg.get_compatible_units('meter')
```

(By the way, we use the word `group` to list collections of units which might have different dimensionality)

I am happy that you find it useful. Let me know if you have other questions.

**Comment by hgrecco** [comment]
I am closing this. Please feel free to reopen or open another if there is any question.

**Comment by elkeschaper** [comment]
Thanks a lot for the very quick reply and help! Very useful!
