### ISSUE TITLE
Missing energy units?

### ISSUE THREAD

**Issue by chrisspen** [hgrecco/pint#454]
I noticed you have several energy units in `default_en.txt`. However, there are several common ones missing, such as Mcf, Ccf, Dth, and MMBtu. Some of these are just multiples of ones you already have, but some are missing and have conversions to existing units as [defined here](https://www.eia.gov/tools/faqs/faq.cfm?id=45&t=8).

Would these be worth adding?

    kilo_watt_hour = 1000 * watt * hour = kWh = kwh = kilowatthour
    one_million_british_thermal_unit = 1000000 * btu = mmbtu = MMBTU = MMBtu
    dekatherm = 10 * therm = dth = Dth
    million_cubic_feet_of_natural_gas = 10.32 * therm = mcf = Mcf = MCF
    centum_cubic_feet = Mcf / 1000.0 = ccf = Ccf

**Comment by onealj** [comment]
If pint relies on string parsing to find the prefix for scaled unit unit (does it), how can it tell if long or short scale[1] prefixes are used?

While even short scale countries seem to recognize [2] the proposed long scale units, does this cause grief on any other software? Is MMBtu any more of a unit than kilometer is? It may be more useful when talking about the scaled or derived units depending on the context, but these aren't base units themselves (I don't think you were trying to make this claim anyways).

I guess the rule for whether a derived unit like Mcf should be included in pint would be the same rule as whether mmHg or inHg count.

[1] https://en.m.wikipedia.org/wiki/Long_and_short_scales
[2] https://www.eia.gov/tools/faqs/faq.cfm?id=45&t=8

**Comment by hgrecco** [comment]
AFAIK, there is no way to distinguish between long and short scale. 

Regarding string parsing. Due to the way it is implemented, when you separate the parts by an underscore (`_`), Pint will not recognise it as prefix and unit (it will recognise as prefix and unit if you join them without any character).

**Comment by tadhgmister** [comment]
not exactly sure where the logic of `MM = 1 000 000` is coming from because in the metric system we'd use the mega `M` prefix for million, since pint fully supports metric prefixes 3 out of 5 of your requested units are directly available:
```
>>> ureg.kilowatt_hour, ureg.kWh
(<Unit('kilowatt_hour')>, <Unit('kilowatt_hour')>)
>>> ureg.Mbtu, ureg.megabtu
(<Unit('megabtu')>, <Unit('megabtu')>)
>>> ureg.dekatherm, ureg.dathm #da is prefix for deca/deka
(<Unit('decathm')>, <Unit('decathm')>)
```

not sure if adding `cubic_feet_of_natural_gas` would work since it seems to be an estimate rather then a well defined derived unit.

**Comment by hgrecco** [comment]
Closing. Feel free to reopen.
