### ISSUE TITLE
ureg.wraps not returning correct units

### ISSUE THREAD

**Issue by alexfeld** [hgrecco/pint#468]
Before, I was able to abbreviate return units, e.g.
 ```python
@ureg.wraps(('kg'), 'meter')
def f(x):
    return x

x = Q_(1., 'meter')
y = f(x)
z = x*y
print z.units
```

Before, the 'kg' was automatically converted to 'kilograms' by `pint`. Now, after updating today from the master branch, if I try the above code I get a `KeyError: u'kg'`

**Comment by hgrecco** [comment]
The reason is that we are not parsing the when building the Quantity without normalizing the unit container. We should change that.

Currently the Quantity constructor accepts:
1. A single value:
  a. a string: which calls Registry.parse_expression
  b. a quantity: which makes a copy
  c. a number/array/etc: which creates a dimensionles Quantity with that as a magnitude a
2. a pair of values M, U:
  a. U is a UnitsContainer or UnitDefinition: creates a Quantity with magnitude M and units U **without normalizing U**
  b. U is string: creates a Quantity with magnitude M and units from Registry.parse_units(U)
  c. U is a SharedRegistryObject (i.e. a Quantity): creates a Quantity with magnitude M and units from U.units (warns if U.magnitude is not 1)

The problem is 2.a, which is intended for internal use when you already know that the UnitsContainer is properly normalized (i.e. the units matches the canonical name in the registry).

I think we should either (1) properly normalize in wraps and/or (2) do it as well in the Quantity constructor but I am afraid that will add an unnecessary overhead. The UnitsContainer is an internal class and therefore the risk of people feeding UnitsContainer object directly to the Quantity constructor is small. A (3) option is flagging normalized/non normalized UnitsContainer (could be a boolean in the UnitsContainer itself). Finally, an (4) option is creating a new constructor for normalized use and leaving `__new__` for unverified stuff.  

I will go for (1) know, but I am leaving the comment complete in case this bytes us in the futur.
