### ISSUE TITLE
Differences between Registry.parse_expression() and Quantity()

### ISSUE THREAD

**Issue by zplizzi** [hgrecco/pint#520]
I find it strange that Registry.parse_expression(string) and Quantity(string) return different values for some input strings, especially since they are described as interchangeable in the docs. 

For example, parse_expression("1") returns int(1), whereas Quantity("1") returns a dimensionless quantity with a value of 1, as desired.

Also, it would be nice if parse_expression could handle ints in addition to strings like Quantity() does.

**Comment by hgrecco** [comment]
`Quantity(string)` calls the quantity constructor and therefore the output is a `Quantity`. `Registry.parse_expression(string)` is more generic, as it parses and evaluates a mathematical expression involving units. Under the hood, `Quantity(string)` calls `Registry.parse_expression(string)` but returns the output wrapped into a `Quantity` (because that is what the user is asking for).

**Comment by hgrecco** [comment]
I am closing this now. Feel free to reopen if unclear.
