### ISSUE TITLE
Handling currencies with Pint

### ISSUE THREAD

**Issue by tartieret** [hgrecco/pint#521]
Hi,

I really like Pint, that I started to use recently. I am working on an engineering system that mix physical units and currencies. For instance, we want to track quantities like "$/kWh"

I assume that I could simply define new units and dimensions such as:
```
usd = [USD] // for US dollars
cad = [CAD] // for canadian dollars
eur = [EUR]
```

and then define a currency context with custom conversion factors between currencies. That would allow to have a changing conversion factor over time.

Is there a better way to do that ? 

Thanks !

**Comment by jetheurer** [comment]
I'm interested in this as well!

**Comment by hgrecco** [comment]
There are a few very good currency specific packages in python. However, if you choose to implement it in pint (because you want it to interoperate with other units) I think that the right way would be to define a currency dimension and then add the different currencies as currency units.
```
usd = [currency]
cad = 0.74 usd
eur = 1.12 usd
```

Of course, the conversion factors are dynamic and therefore maybe is a good idea to fetch them from a database periodically or when the program start.

**Comment by vinokurov** [comment]
I was also experimenting with Pint for doing units and currency conversions. I tend to like the context approach more because it allows me to specify conversion rates. However I found there are some limitations.

For example.
```
#Currency
EUR = [eur]
GBP = [gbp]
pence = 0.01 * GBP

@context(eurgbp=1.0) fx
    #[gbp] <-> [eur]: value * eurgbp
    [gbp] -> [eur]: value / (eurgbp GBP/EUR)
    [eur] -> [gbp]: value * (eurgbp GBP/EUR)
@end
```

This works:
```
ureg = pint.UnitRegistry('my_pint.txt')
amount = 100 * ureg.GBP
amount.to('EUR', eurgbp=0.88)

>>> 113.636363636 EUR
```

This doesn't work:
```
price = 25 * ureg.EUR/ureg.MWh
price.to('GBP/MWh', 'fx', eurgbp=0.88)

>>> DimensionalityError: Cannot convert from 'EUR / megawatt_hour' ([eur] * [time] ** 2 / [length] ** 2 / [mass]) to 'GBP / megawatt_hour' ([gbp] * [time] ** 2 / [length] ** 2 / [mass])
```

@tartieret , above you mentioned you were using the mix of currencies and physical units. Did you have the same issue?

**Comment by westurner** [comment]
> There are a few very good currency specific packages in python. 

@hgrecco What would you point users to or recommend for handling calculations involving currency quantities (and units)?

- "Integration with pint and uncertainties"
  https://github.com/limist/py-moneyed/issues/115

  > It would be very useful to be able to work with py-moneyed, pint, and uncertainties. Has someone already accomplished this or similar (maybe by integrating statistical distributions)?

**Comment by hgrecco** [comment]
Closing due to #938

**Comment by westurner** [comment]
FWIW, integration with e.g. py-moneyed would still be great. django-money, which is implemented atop py-moneyed:
- has database models, form fields, and validators implemented for persisting currency values to a SQL database with the Django ORM
- can pull exchange rates from https://openexchangerates.org/ and https://fixer.io/ : https://django-money.readthedocs.io/en/stable/#working-with-exchange-rates

**Comment by hgrecco** [comment]
@westurner As I mentioned in #938, I would very much welcome such thing as an external package.
