### ISSUE TITLE
(Bug?) parsing expressions of the kind "600mg/24h"

### ISSUE THREAD

**Issue by alvaroabascar** [hgrecco/pint#555]
I've noticed that expressions of the kind `[number1] [units1] / [number2] [units2]` are incorrectly parsed: respecting the order of operations in this case leads to the tree `'(((num1 * unit1) / num2) * unit2)'`, but the actual tree (as intended by the human writing the expression) would be `'((num1 * unit1) / (num2 * unit2))'`.

Example:

```python
from pint import UnitRegistry
reg = UnitRegistry()
q = reg.parse_expression('600mg/24hours')
# out: <Quantity(25.0, 'hour * milligram')>
# output should be:  <Quantity(6.944444444444444e-09, 'kilogram / second')>
```

**Comment by hgrecco** [comment]
This is a tough call because it has to be unambiguous. Maybe we can open this for a wider debate and hear opinions.

**Comment by dalito** [comment]
Pint´s rule is that units are treated exactly like numbers, So pint behaves as specified. However, I agree with @alvaroabascar that the rule contradicts the expectations.  Even after inserting brackets the result stays the same:
```
>>> reg.parse_expression('600mg/(24hours)')
<Quantity(25.0, 'milligram / hour')>
```

@hgrecco do you have any specific ambiguous examples in mind?

**Comment by hgrecco** [comment]
Let me elaborate just to add to the discussion. I think that it might be very confusing because we might have to put rules regarding spacing. We could change the precedence rules and say that units to the right of a number are one element. In this case: what next would mean (together, separated by space(s), by `*`)? Is always clear the intention of the user?

For example:

- `600mg/(24hours)` => `25 mg / hour` 
No issue here.
- `600mg/24hours` => `25 mg / hour`
Intuitively I would say `24hours` is one element.
- `600mg/24 hours`  => ?
Because hours is a unit, you could say `24 hours` is one element and the output should be `25 mg / hour`. However, following the easy to remember rule that units are exactly like numbers, the result is 25 mg * hour.
- `600mg/24*hours`  => ?
Same problem here. What is the intention of the user? 

If the last means 25 mg * hour, does it make sense that `600mg/24hours`, `600mg/24 hours` and `600mg/24*hours` give different results?

The approach in Pint is that we should not guess user intention because it might lead to subtle bugs.

**Comment by dalito** [comment]
Thanks for the examples. I would also prefer to keep the rules in Pint simple and unambiguous. We should add a note about the behaviour to the docs (in Tutorial / String Parsing). I'll send a PR in the next days.

**Comment by bilderbuchi** [comment]
Probably related: #536

**Comment by alvaroabascar** [comment]
@hgrecco I guess that when visually analyzing such expressions, we see units and numbers as two separate blocks, and our mental process, in the case of "600 mg/24h" is closer to: `divide 600 by 24, divide "mg" by "h" and then apply the units "mg/h" to the quanity 600/24=25`, than it is to `multiply 600 by "mg",  24 by "h" and then divide "600mg" by "24h".`

Anyway it seems reasonable for me to keep the rules simple and "not guess", although this should definitely be documented (thanks @dalito ). In my case it came as a big surprise!

**Comment by duelafn** [comment]
Forgive the drive-by comment, but preserving the existing rules is nice for legacy code. Though, to confound the issue, I'll add the parsing behavior from GNU units which I've always found fairly natural. It treats all implicit multiplication as higher-precedence:

    $ units '600mg/(24hours)'
        Definition: 6.9444444e-09 kg / s
    $ units '600mg/24hours'
        Definition: 6.9444444e-09 kg / s
    $ units '600mg/24 hours'
        Definition: 6.9444444e-09 kg / s
    $ units '600mg/24*hours'
        Definition: 0.09 kg s
    $ units '600 mg/24hr'
        Definition: 6.9444444e-09 kg / s

**Comment by hgrecco** [comment]
Closing. Feel free to reopen if needed or create a new issue for parsing rules
