### ISSUE TITLE
Support inequalities

### ISSUE THREAD

**Issue by KOLANICH** [hgrecco/pint#575]
Often  "> some quantity"  is written in some specs. I think it'd be nice to parse and use in calculations such kind of quantities.

**Comment by onealj** [comment]
What did you have in mind?

Keep in mind that a spec is not a quantity. It's a quantity and a criteria. You can't add or subtract a spec (do you linearly add or RMS the values, what happens if the criteria differs)--you can only add quantities and carry over a criteria.

This might belong in a different package or library for handling specs. For example, we have uncertainties to handle measurement error and error propagation (5.0 ± 0.1 m).

**Comment by hgrecco** [comment]
Closing. Feel free to reopen or reformulate.
