### ISSUE TITLE
question: defining units with offsets 

### ISSUE THREAD

**Issue by weAllWeGot** [hgrecco/pint#591]
Hi this module is superrr dope.
but i have one question regarding defining a new unit with an offset. 
I thought I might find something in the documentation but I haven't

If i want to define a unit for pounds per square inch gauge `psig` , 
the equation is psig = psi-14.7, going off the `degC` definition as an example I thought the syntax would be the following.

```
ureg.define('psig = psi; offset:14.7')
```

but this is the result I get when I try the conversion.
```
p = Q_(75,'psi')
p.to('psig')
>>> <Quantity(517106782.288,'psig')>
```
but I expected a value of 60.3

Looking further into this I also realize I don't quite understand how the syntax definition for conversion from Kelvin to Fahrenheit and Rankine work. 

Thanks! and sorry if this is covered somewhere in the docs that I just missed.

**Comment by srgkoshelev** [comment]
I have encountered that issue some time ago. When you specify both value and offset in Pint you have to use "default" units. Those are different from base units (because kilo is a prefix). If you haven't tweaked anything then for pressure default units will be `g/(m*s**2)`. For 1 psi the value will be `6.895*10**6 * g/(m*s**2)`.

Here's my line from definitions file:
`psig = 6.895*10**6 * g/(m*s**2); offset: 14.696*6.895*10**6 = pound_force_per_square_inch_gauge `

Hope this helps.

**Comment by weAllWeGot** [comment]
Ah great thanks for this information, ill give this definition a try! 
I feel like this would be a useful example/explanation to add to the documentation on defining units. I'll try and start a PR
