### ISSUE TITLE
Problem using @preg.chek in a class context

### ISSUE THREAD

**Issue by jamasi** [hgrecco/pint#621]
I'm trying to define a simple class to store the dimensions of an object using pint-0.8.1:

```python
import pint
ureg = pint.UnitRegistry()


class Dimensions(object):
    """This helper class should be used to set dimension properties for objects
    """
    @ureg.check(None, "[]", "[]", "[]", "[length]")
    def __init__(self, length=0.0, width=0.0, height=0.0, unit=ureg.m):
        self.length = length
        self.width = width
        self.height = height
        self.unit = unit
```

Trying to instantiate a new Dimensions object triggers this error:
> AttributeError: 'NoneType' object has no attribute 'dimensionality'
if one does not specify the unit parameter and
> AttributeError: 'Dimensions' object has no attribute 'dimensionality'
if one does specify it (looks like self is checked).

One way around this would be to have an explicit ureg.check_param(variable, dimension_spec) call that would return True or False (or ureg.assert(variable, dimension_spec) that would raise an exception.

Maybe such functionality already exists, but I could not easily find it in the docs (or the code) therefore I'm opening this issue.

**Comment by hgrecco** [comment]
I think that the real problem is default values which are not properly handled.

This works:
```python
x = Dimensions(1, 1, 1, 1 * ureg.meter)
```
This raises an error (as expected):
```python
x = Dimensions(1, 1, 1, 1 * ureg.kilogram)
```

This is an unexpected failure:
```
x = Dimensions(1, 1, 1)
```

For a while I have been trying to find time to migrate all this code to the new [signature](https://docs.python.org/3/library/inspect.html#introspecting-callables-with-the-signature-object) which will make everything more robust. Volunteers?

**Comment by hgrecco** [comment]
Linking to #1753
