### ISSUE TITLE
Autodocumenting modules, classes, and functions for pint

### ISSUE THREAD

**Issue by jondoesntgit** [hgrecco/pint#665]
Any qualms about using sphinx's autodocumentation features for documenting the various modules, classes, and functions?

I imported the docs into Dash today via doc2dash, and found that Dash couldn't find any of the methods.... I think that if we did some auto-documentation of all the code, that would improve the coverage.

**Comment by Tigraan** [comment]
The short version is that #835 kinda fixed that issue.

#835 added the ["developer reference" page](https://pint.readthedocs.io/en/latest/developers_reference.html) to the doc. It also modified the `objects.inv` file (make sure to point your intersphinx to https://pint.readthedocs.io/en/latest/ and not https://pint.readthedocs.io/en/0.9/), which I guess that Dash uses (if it was inspecting the sources, it would have found the docstrings already).

That being said, it's not a panacea, since not all is documented. For instance, [`pint.quantity._Quantity`](https://github.com/hgrecco/pint/blob/master/pint/quantity.py#L97) is not autodoc'ed ([because it is a private method](https://stackoverflow.com/questions/1149280/how-can-i-use-sphinx-autodoc-extension-for-private-methods)) , and [`pint.quantity.Quantity`](https://github.com/hgrecco/pint/blob/master/pint/quantity.py#L1743) is not either (because it has no docstring).

**Comment by hgrecco** [comment]
Shall we close this isuue for the time being?

**Comment by hgrecco** [comment]
Closing. Feel free to reopen if needed.
