### ISSUE TITLE
__array_wrap__ broken for `insert`, etc.

### ISSUE THREAD

**Issue by dopplershift** [hgrecco/pint#682]
The following code:
```python
import numpy as np
import pint
ureg = pint.UnitRegistry()
a = np.arange(3) * ureg.meter
np.insert(a, 2, 4 * ureg.meter)
```
produces:
```pytb
~/miniconda3/envs/py36/lib/python3.6/site-packages/numpy/lib/function_base.py in insert(arr, obj, values, axis)
   4439         new[tuple(slobj)] = arr[tuple(slobj2)]
   4440         if wrap:
-> 4441             return wrap(new)
   4442         return new
   4443     elif indices.size == 0 and not isinstance(obj, np.ndarray):

~/miniconda3/envs/py36/lib/python3.6/site-packages/pint/quantity.py in __array_wrap__(self, obj, context)
   1342 
   1343     def __array_wrap__(self, obj, context=None):
-> 1344         uf, objs, i_out = context
   1345 
   1346         # if this ufunc is not handled by Pint, pass it to the magnitude.

TypeError: 'NoneType' object is not iterable
```

I have no idea if `insert` has any hope of working right now, but that exception comes from code that is obviously wrong:

https://github.com/hgrecco/pint/blob/241bf7df1404e26d202df64e12e772d111803c31/pint/quantity.py#L1428-L1430

Here `context` defaults to `None` (as is [documented for numpy](https://docs.scipy.org/doc/numpy/reference/arrays.classes.html#numpy.class.__array_wrap__)), but the first line in `__array_wrap__` tries to unpack it unconditionally. I have no idea what the right behavior is in this case.

**Comment by hgrecco** [comment]
Revisit after #905

**Comment by jthielen** [comment]
Based on https://docs.scipy.org/doc/numpy-1.17.0/reference/arrays.classes.html#numpy.class.__array_ufunc__, it looks like `__array_wrap__` is disabled since `__array_ufunc__` is defined (thus why `__array_wrap__` has been removed in #905), so I don't think this problematic code is reached even now?

`np.insert` would be a good `__array_function__` implementation to add either in #905 or a follow-up.
