### ISSUE TITLE
The __array_function__ protocol for overriding NumPy's API

### ISSUE THREAD

**Issue by shoyer** [hgrecco/pint#790]
We have been drafting a new protocol to allow for overriding NumPy functions, e.g., for `np.concatenate`: http://www.numpy.org/neps/nep-0018-array-function-protocol.html

It would be great to experiment with getting this working in pint, since arrays with units are one of the intended use-cases.

**Comment by hgrecco** [comment]
Thanks for writing. I have been looking forward to see something like this implemented in numpy and we have indeed played with the array function protocol. See #753 (and cc: @andrewgsavage )

I was wondering if you can clarify something that is not clear to me. Will this solve the `asanyarray` issue or we will still need to subclass? AFAIK NumPy functions do not like duck typing. You MUST derive from ndarrary to make some functions work because np.asanyarray() which is called frequently only allows only strict subclasses.

**Comment by shoyer** [comment]
> AFAIK NumPy functions do not like duck typing. You MUST derive from ndarrary to make some functions work because np.asanyarray() which is called frequently only allows only strict subclasses.

It is arguably worse than this -- many NumPy functions (e.g., `np.concatenate()`) use `np.asarray()` internally, which converts subclasses into base-class instances. This is mostly a historical artifact, because NumPy comes with some non-substitutable subclasses (namely, MaskedArray and `np.matrix`).

`__array_function__` is intended to work without subclassing, but you *do* need to define operations with units for all numpy array functions you'll want to support. Fortunately this usually be done in a fairly mindless way.
