### ISSUE TITLE
ureg.wraps for optional return values

### ISSUE THREAD

**Issue by elihunter173** [hgrecco/pint#894]
Does `ureg.wraps` support optional return values?

In the code base I work on, we've been gradually introducing pint to help us manage units. In many places we have functions that either return the result of some calculation, or `None` if the calculation cannot work for whatever reason.

Here's a fairly contrived example:

```python
@ureg.wraps(
    (ureg.meter, ureg.meter),
    (ureg.meter, ureg.meter),
    strict=False,
)
def example(a: float, b: float) -> Optional[Tuple[float, float]]:
    if a < 0 or b < 0:
        return None
    else:
        return b, a
```

Is there any support for this currently? We've been using `None` as the return in `ureg.wraps` to skip conversion, but we'd rather get a unit-ed return in the case where the calculation succeeds.

**Comment by make-ing** [comment]
i'm pretty sure it is not supported... look at the implementation of wraps [here](https://github.com/hgrecco/pint/blob/33d1979ff3fc0c6b0c5fc2cc1d8612f670821d8d/pint/registry_helpers.py#L148).

Since you are allready using non-strict, you can handle this inside the function yourself. wraps is just a helper function to make adaption easier, but in this case i think there is no way around handling this yourself like so:
```
@ureg.wraps(
    None,
    (ureg.meter, ureg.meter),
    strict=False,
)
def example(a, b):
    if a < 0 or b < 0:
        return None
    else:
        return ureg.Quantity(b, 'meter'), ureg.Quantity(a, 'meter')
```

**Comment by hgrecco** [comment]
This is indeed not supported (yet). In my case, I usually raise an error in this type of cases,

**Comment by hgrecco** [comment]
Linking this to #1753
