### ISSUE TITLE
Quantity string parsing has unexpected behavior

### ISSUE THREAD

**Issue by JRice15** [hgrecco/pint#896]
I have found that when creating a new quantity in the following manner: 

`q = Quantity("15", "meters")`

The magnitude stays as a string, not parsed as an integer as one might expect. It can manifest in very wrong results later, such as:

`print(q * 2) // "1515 meter"`

The issue is not present in the similar situation of passing one string for both magnitude and units:

`q = Quantity("15 meters")
print(q * 2) // "30 meter"

I understand if there is possibly a reason for this behavior, but as it is not warned against or noted in the docs I suspect is not intended. I suspect a line or two of code somewhere would solve the problem easily.

[pint v0.9]

**Comment by hgrecco** [comment]
Yep. The problem is that Pint allows any type for the magnitude, leaving to the user that it makes sense. That is why you can use a numpy array, a float, an int, a fraction or any other numerical type (which pint might not be aware of). It is true that this flexibility brings unexpected consequences.
