### ISSUE TITLE
unintuitive behaviour interacting with numpy scalars

### ISSUE THREAD

**Issue by Michaeldz36** [hgrecco/pint#900]
```python
import pint, numpy
si = pint.UnitRegistry()

a = numpy.ones(1)
b = 10. * si.gram / si.kilogram
print(a[0]+b, "vs.", float(a[0])+b)
```
```
11.0 gram / kilogram vs. 1.01 dimensionless
```

**Comment by jthielen** [comment]
I think this is a bigger issue in general with NumPy's deferring to pint for operator precedence not working properly. The following code (with arrays) demonstrates the same issue:

```python
import pint, numpy
si = pint.UnitRegistry()

a = numpy.array([0, 1, 2])
b = 10. * si.gram / si.kilogram
print(a + b, "vs.", b + a)
```

```
[10.0 11.0 12.0] gram / kilogram vs. [0.01 1.01 2.01] dimensionless
```

It looks like some more subtle debugging of why the bare NumPy array/scalar is not treated as dimensionless in the first example is need.

**Comment by Tigraan** [comment]
I guess "unintuitive behaviour" is the British way to say "buggy"...

Even more generally, the problem seems to be that (numpy array) + (pint array) is a valid operation regardless of the dimensions which is surely a bug:

```python
import pint, numpy
si = pint.UnitRegistry()

numpy.asarray([1.0, 2.0]) + 10.* si.gram  # [2.0, 3.0] gram
1.0 + 10.0 * si.gram  # pint.errors.DimensionalityError: Cannot convert from 'gram' to 'dimensionless'
```

One could argue that the first behaviour (add to the magnitude) is proper (I do not think so), but surely one cannot argue that floats and ndarrays should behave differently.

Looking at the definition in pint (https://github.com/hgrecco/pint/blob/e6ae929ec13db8413ab3645f0fdddb10d7fd6704/pint/quantity.py#L719) the addition operation seems kosher. My best guess is that numpy accepts operations of the form (array) + (some other object) with restrictions lax enough that pint arrays qualify, but I have not checked.

**Comment by jthielen** [comment]
This *should* be resolved with #905 (see test added below):

 https://github.com/hgrecco/pint/blob/43fbae24028edcffaf855916d7c68889b93786e0/pint/testsuite/test_numpy.py#L327-L331

@Michaeldz36 and @Tigraan would you be able to confirm if this is resolved for you on the current master branch?

**Comment by jthielen** [comment]
Unless there are complaints, I think this can be closed now @hgrecco? There was a test added in #905 for this issue (see above comment).

**Comment by hgrecco** [comment]
Closing. @Michaeldz36 and @Tigraan , feel free to write back if needed.
