### ISSUE TITLE
Reversible (<->) context conversion rates

### ISSUE THREAD

**Issue by crusaderky** [hgrecco/pint#995]
Reversible conversion rates in contexts (``<->`` symbol) only work in some cases.

These work:
```
@context(n=1) spectroscopy = sp
    [length] <-> [frequency]: speed_of_light / n / value
    [wavenumber] <-> [length]: 1 / value
@end
```
But this doesn't:
```
@context water
    [volume] <-> [mass]: value * 1 kg/l
@end
```
```python
>>> ureg.Quantity("1 l").to("kg", "water")
1.0 <Unit('kilogram')>
>>> ureg.Quantity("1 kg").to("l", "water")
pint.errors.DimensionalityError: Cannot convert from 'kilogram ** 2 / liter' ([mass] ** 2 / [length] ** 3) to 'liter' ([length] ** 3)
```

I'm unsure why ``[length] <-> [frequency]`` instead works.

The workaround is to write two monodirectional conversions:
```
@context water
    [volume] -> [mass]: value * 1 kg/l
    [mass] -> [volume]: value / (1 kg/l)
@end
```

Pint could auto-recognize the linear use case ``y = mx+q``, which to my knowledge covers 100% of units, and automatically reverse it. Exotic formulas e.g. value^konst or konst^value should not be reversible and trigger a crash in Context.from_lines.

**Comment by hgrecco** [comment]
Indeed, this is a desirable feature. At the time Context was implemented, we chose only to support the very simple 1/x because it was trivial to code. We decided to see how the feature was used in the field and only if it was necessary to code the necessary logic to invert a function (or determine that we will not do it and raise an exception for exotic formulas.
